server:
  port: 8082
spring:
  boot:
    admin:
      client:
        url: http://localhost:1111

management:
  endpoints:
    web:
      exposure:
        include: "*"

message: "This is a demo-api message from config server"
