spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring_rest
    username: root
    password: Vishnu@11
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  boot:
    admin:
      client:
        url: http://localhost:1111

management:
  endpoints:
    web:
      exposure:
        include: "*"

server:
  port: 8083
